### PR TITLE
Add compile option --strictNullChecks

### PR DESCRIPTION
**Pull request by yoshimasa36g**
- Add compile option --strictNullChecks
- Remove null or undefined checks from validate condition
- Add DateValue as ValueObject

### CODE REVIEW

**Comment by MasayukiFukada** [comment]
@yoshimasa36g 
I saw some 'sapn'.

**Comment by yoshimasa36g** [comment]
@MasayukiFukada Oops, I Fixed it.

**Comment by MasayukiFukada** [comment]
OK.
LGTM

**Comment by yoshimasa36g** [comment]
Merge #15 and fix null checks

**Pull request merged**
