### PR TITLE
Modify test data and coveralls calling

### PR DESCRIPTION
**Pull request by yoshimasa36g**
- Modify date format of test data
    - Because to avoid warning from moment
    - We might need converter
        - It convert from `YYYY/MM/DD HH:mm:ss` to `YYYY-MM-DDTHH:mm:ss` (ISO8601)
- Move coveralls calling from coverage.sh to npm script
- Fix lint issue

### CODE REVIEW

**Comment by yoshimasa36g** [comment]
hmm... coveralls not working :cry:

**Comment by MasayukiFukada** [comment]
@yoshimasa36g Is 'after_success' not working ?

**Comment by yoshimasa36g** [comment]
@MasayukiFukada No. after_success is working. coveralls got error.

https://travis-ci.org/yoshimasa36g/youkan/builds/172954008

**Comment by MasayukiFukada** [comment]
I'm worried about 'Icov.info' is not exist.

**Comment by yoshimasa36g** [comment]
@MasayukiFukada It's exists. 

https://travis-ci.org/yoshimasa36g/youkan/builds/172971495
see line 782-1074

**Comment by MasayukiFukada** [comment]
LGTM
:sake:

**Pull request merged**
