### PR TITLE
Add User

### PR DESCRIPTION
**Pull request by MasayukiFukada**
Add User as Model

### CODE REVIEW

**Comment by yoshimasa36g** [comment]
@MasayukiFukada I think that the behavior of Identity in the toObject method should be unified.

It is different from the existing Phase class.

**Comment by MasayukiFukada** [comment]
I fixed it, but how is it?

**Comment by yoshimasa36g** [comment]
@MasayukiFukada The behavior of the toObject method is still different.

```typescript
// Phase
{
    id: { ... },
    name: { ... },
    dateSpan: { ... }
}
```

```typescript
{
    userIdentity: {
        id: { ... },
        name: { ... }
    },
    role: { ... }
}
```

In order to unify behavior of Phase class and User class, we need to unwrap userIdentity.
Or we need to wrap the id and name of Phase class.
(Also in this case userIdentity of User class is redundant as `user`, so I think better to just set it to` identity`)
Which do you like?

**Comment by MasayukiFukada** [comment]
I was wrapping it because I was concerned that ID of Role and ID of UserIdentity overlapped. Since there is no problem if Role wraps, I think that UserIdentity has no problem by unwrap.

**Comment by yoshimasa36g** [comment]
@MasayukiFukada LGTM

[LGTM](https://lgtm.in/i/S7w6Fhpqq)

But I'm slightly worry that the process of creating the expected result (createUserObject) and the process of making the actual value (toObject) are almost the same.

**Pull request merged**
