### PR TITLE
Add Role Id

### PR DESCRIPTION
**Pull request by MasayukiFukada**
* Add Role Id as ValueObject

### CODE REVIEW

**Comment by yoshimasa36g** [comment]
@MasayukiFukada Perhaps, `isValid` must check id is greater than zero.

**Comment by MasayukiFukada** [comment]
@yoshimasa36g Oops, good point.Fix it.

**Comment by MasayukiFukada** [comment]
I misunderstood. I thought 'greater than zero' is including zero. :-p

**Comment by yoshimasa36g** [comment]
@MasayukiFukada LGTM

[LGTM](https://lgtm.in/i/8q52DbuOp)

**Pull request merged**
